config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # About pages
  get "/about/" => "about#show", page: "home"
  get "/about/:page" => "about#show"

  # Dashboard
  get '/profile' => "users#show", as: "profile"

  # Managing users
  get '/register' => 'users#new', as: "register"
  post '/users' => 'users#create', as: "register_submit"
  get '/activate/:token' => 'users#activate', as: "activate"
  get '/resend-activation' => 'users#resend_activation', as: "resend_activation"

  # Managing sessions
  get '/login' => 'sessions#new', as: "login"
  post '/login' => 'sessions#create', as: "login_submit"
  get '/logout' => 'sessions#destroy', as: "logout"

  root "about#show", page: "home", as: "home"
end

app/views/shared/_flash.html.haml
- flash.each do |key, value|
  %div(class="flash-#{key}")
    = value.html_safe

app/views/shared/_header.html.haml
%header#header
  #brand
    = link_to "ISOTOPE", home_path

app/views/shared/_login.html.haml
%h3 Login
= form_tag login_submit_path, id: "login-form" do
  = text_field_tag :email_or_username, "", placeholder: "Email or Username"
  = password_field_tag :password, "", placeholder: "Password"
  = label_tag :remember, id: "remember-label" do
    = check_box_tag :remember
    Remember me?

  - if params.key?(:redirect_to)
    = hidden_field_tag(:redirect_to, params[:redirect_to])
  = submit_tag "Submit"
  %span.register-or-login-switch
    or
    = link_to "create a new account", register_path, id: "register-link"

app/views/shared/_login_or_register.html.haml
#login-or-register
  #login-panel
    = render 'shared/login'
  #register-panel(style="display: none")
    = render 'shared/register'

= content_for :body_script do
  :coffee
    $ ->
      $("#register-link").click (e) ->
        $("#login-panel").fadeOut 100, ->
          $("#register-panel").fadeIn 100
        e.preventDefault()
      $("#login-link").click (e) ->
        $("#register-panel").fadeOut 100, ->
          $("#login-panel").fadeIn 100
        e.preventDefault()

app/views/shared/_register.html.haml
%h3 Register

= form_for :user, url: register_submit_path, html: {id: "register-form"} do |f|
  .validated
    = f.text_field :username, placeholder: "Username", required: "", pattern: "^[A-Za-z0-9\.\-\_]{3,50}$", title: "Must be 3 to 50 characters (alphanumerics, periods, dashes, or underscores)"
    .hint
  .validated
    = f.text_field :email, placeholder: "Email", required: "", type: "email", title: "Must be a valid email"
    .hint
  = f.text_field :first_name, placeholder: "First name"
  = f.text_field :last_name, placeholder: "Last name"
  .validated
    = f.password_field :password, placeholder: "Password", required: "", pattern: ".{6,50}", title: "Must be 6 to 50 characters"
    .hint
  .validated
    = f.password_field :password_confirmation, placeholder: "Confirm password", required: "", title: "Passwords must match"
    .hint
  = f.submit "Submit"
  %span.register-or-login-switch
    or
    = link_to "log into an existing account", login_path, id: "login-link"

= content_for :body_script do
  :coffee
    $ ->
      $("#user_password_confirmation").on "input", ->
        if this.value != $('#user_password').val()
          this.setCustomValidity 'Passwords must match'
        else
          # input is valid -- reset the error message
          this.setCustomValidity ''
        return